### ISSUE TITLE
Great Project - Question About Docs

### ISSUE THREAD

**Issue by mweth** [marella/chatdocs#1]
Is there an overview or guide as to which kinds of documents this can handle or what interim steps are needed to -- for example process doc, docx, ppt, or pdf files?

**Comment by migueltorres** [comment]
Since it's based on privateGPT, I guess the supported document type list is this one: https://github.com/imartinez/privateGPT#instructions-for-ingesting-your-own-dataset

**Comment by marella** [comment]
Thanks. I added them to the README under [Features](https://github.com/marella/chatdocs#features) section.
