### ISSUE TITLE
is it possible to reset DB ?

### ISSUE THREAD

**Issue by gandolfi974** [marella/chatdocs#11]
hello,
i have upload document and after delete them but the LLM have this dcoument in memory.
How i can reset memroy or refresh the document list ?

thanks

**Comment by marella** [comment]
Hi, you can delete the `db` directory and add documents again.
You should also restart the UI by stopping (`ctrl + c`) and starting (`chatdocs ui`) it again after adding documents.

**Comment by gandolfi974** [comment]
thanks.
it would be nice to have a command in the interface or on the command line that does this automatically. Depending on the project, you don't need the same documents to consult, and this can quickly become a big mix-up.
