### ISSUE TITLE
Feature: --listen

### ISSUE THREAD

**Issue by pyrater** [marella/chatdocs#15]
Is there a way to add the --listen flag to access the ui from other computers on the net. Would it be as simple as me changing line 63 in util.py
from    app.run(host="localhost", port=config["port"], use_reloader=False)
to    app.run(host="0.0.0.0", port=config["port"], use_reloader=False) ?

**Comment by MichaelMurithi** [comment]
I tried changing the `host` and `port` in `app.run()` to make it accessible to the internet but unfortunately it did not work for me. 
As you suggested, I think it is a feature that can be considered.

**Comment by pyrater** [comment]
Got it to work by doing this:

1. open chatdocs.yml and add ip: 0.0.0.0 above the port line. 

![image](https://github.com/marella/chatdocs/assets/6691563/5f978879-41a3-46e3-9637-4d3a5dcfc4b8)

2. Open ui.py and replace localhost on line 63 with config["ip"]
![image](https://github.com/marella/chatdocs/assets/6691563/3de879a4-3e04-422c-81b0-c77eff8bf5f8)

then open a cmd window like your going to run chatdocs ui but instead do:
pip uninstall chatdocs  
pip install ./

This will reinstall / install with the new changes and it will be able to be accessed via the network.
