### ISSUE TITLE
What would be the best way to implement web scraping into this solution?

### ISSUE THREAD

**Issue by shaddekhan** [marella/chatdocs#23]
Hi again,

I am looking into langchain and there are so many tools available (doc loaders). I am looking at making this solution go online and scrape websites as an alternative to documents. How would you suggest to do that as easily as possible?

**Comment by marella** [comment]
Hi, you can look at tools like [scrapy](https://scrapy.org/) but you should also check the copyright/license, robots.txt etc of websites to see if you are allowed to scrape them.
