### ISSUE TITLE
How does one uninstall everything?

### ISSUE THREAD

**Issue by Ananderz** [marella/chatdocs#26]
Hi,

I have found most of the folders that this package installs to, it's quite spread out on Windows. Is there a good way to uninstall everything if needed?

**Comment by marella** [comment]
Hi,

- `pip uninstall chatdocs` will uninstall the tool. You can use Python [virtual environments](https://docs.python.org/3/library/venv.html) to install which will make uninstalling easier as you can just delete the `venv` directory.
- `C:\Users\USERNAME\.cache\huggingface\hub` contains downloaded models.
- `C:\Users\USERNAME\AppData\Roaming\nltk_data` may contain some downloaded data.
