### ISSUE TITLE
Does the falcon models work with chatdocs ?

### ISSUE THREAD

**Issue by Ananderz** [marella/chatdocs#35]
I know the falcon models are a little different and that they might not work with Chatdocs. Have anyone tried and got it to run. Which model did you use? GGML, GPTQ or maybe the standard models?

**Comment by nickorrnah** [comment]
Any update on this?  Been trying to get the 7b falcon model to work through GGML, but it seems to never recognize the files properly as GGML.

**Comment by marella** [comment]
Support for the new GGML Falcon models was added recently in ctransformers 0.2.12 Make sure you have installed the latest version:

```sh
pip install 'ctransformers>=0.2.12'
```

You can find the falcon GGML models [here](https://huggingface.co/TheBloke). Example:

- https://huggingface.co/TheBloke/falcon-7b-instruct-GGML
- https://huggingface.co/TheBloke/WizardLM-Uncensored-Falcon-7B-GGML

Normal HF and GPTQ versions should also work.
