### ISSUE TITLE
Config to Limit Chatdoc responses only to documents added

### ISSUE THREAD

**Issue by virajpai** [marella/chatdocs#38]
First of all, this is an amazing tool for offline Q&A modules. 

Wanted to check if there is a config available in chatdocs.yml file to limit responses only to documents added and reply open questions with standard "I don't know" responses.

Or at least set the temperature of the models used to ensure the answers are not made using LLMs pre-trained texts.

**Comment by marella** [comment]
There is no config option for that. It is hard to make LLMs not to use their own knowledge. This is already being discussed in #29 like trying different prompts etc., but there is no good solution yet.
To set temperature, see https://github.com/marella/chatdocs/issues/40#issuecomment-1624070024 but I don' think it will help.
Closing this in favor of #29.
