### ISSUE TITLE
chunksize and max_seq_length of embedding not matching

### ISSUE THREAD

**Issue by 94bb494nd41f** [marella/chatdocs#39]
AFAIK the default of the length measure ` RecursiveCharacterTextSplitter` is `len` while it is some token measure for the instrutor embeddings.

The programm still works, however chunks inserted into the database a smaller than one would suspect.

**Comment by marella** [comment]
As long as the context size of model is higher than the tokens in chunk, it should be fine.
Since tokenization is dependent on model, `RecursiveCharacterTextSplitter` or other preprocessors will not know about the tokens.
