### ISSUE TITLE
Incomplete response

### ISSUE THREAD

**Issue by ChrisBNECBT** [marella/chatdocs#43]
The response of a query is incomplete. ChatGPT3.5 allows users to prompt it to continue with the response in a new prompt and the team at Oobabooga added a "Continue" button to their WebUI to do the same.

There is no way to continue lost response currently through a new prompt and splitting the prompts into smaller chunks resulted in a lost of context when responding.

I'm unsure whether this is a bug or missing feature and am wondering is there a fix to allow a full response.

I'm new to this.

![Screenshot 2023-07-09 at 08-47-17 ChatDocs](https://github.com/marella/chatdocs/assets/137929222/205debcd-f023-44bf-bdf5-36b4cfa260bf)

**Comment by marella** [comment]
You can increase `max_new_tokens` (default is `256`) to get longer responses:

```yml
ctransformers:
  config:
    max_new_tokens: 500 # increase this value
```

Related to #28
