### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by flourishing** [marella/chatdocs#46]
hello. i installed chatdocs as th docs.

when i  installed and chatdoc download the model, and then add the docs.
chatdocs add /root/docs
and then run chatdocs ui
it reports
Illegal instruction

`root@9bb4ee29f890:~# chatdocs add /root/docs
Creating new vectorstore
Loading documents from /root/docs
Loading new documents: 100%|██████████████████████| 1/1 [00:00<00:00, 41.39it/s]
Loaded 1 new documents from /root/docs
Creating embeddings. May take a few minutes...
load INSTRUCTOR_Transformer
max_seq_length  512
root@9bb4ee29f890:~# chatdocs ui

load INSTRUCTOR_Transformer

max_seq_length  512
Illegal instruction`

**Comment by marella** [comment]
Can you please your processor name. Please try adding the following to your `chatdocs.yml`:

```yml
ctransformers:
  lib: avx
```

If it still doesn't work, change `avx` to `basic`:

```yml
ctransformers:
  lib: basic
```

**Comment by marella** [comment]
In the latest version of `ctransformers` this is automatically handled, so if you just update `ctransformers`, above changes to `chatdocs.yml` are not required:

```sh
pip install 'ctransformers>=0.2.21'
```
