### ISSUE TITLE
Not using chatdocs.yml

### ISSUE THREAD

**Issue by abhishekrai43** [marella/chatdocs#54]
chatdocs download --config C:\Users\Administrator\Documents\chatdocs\chatdocs.yml

Tried this variation

chatdocs download --config chatdocs.yml

Still does not use it. 

How to pass this to chatdocs ui command to ensure it uses GPU and the model there in? Is this a recent change?

**Comment by abhishekrai43** [comment]
Fixed it the main.py

**Comment by williamblair333** [comment]
@abhishekrai43 Would you elaborate on the fix?
