### ISSUE TITLE
Responses get cut off in the middle.

### ISSUE THREAD

**Issue by nickorrnah** [marella/chatdocs#56]
I often find that whenever I have a response around 2 paragraphs or so in length that the response just gets cut off and does not fully complete.  Is there a config setting to increase max response length or some other way to get around this issue?

**Comment by Ananderz** [comment]
Increase your max_new_tokens in the config.yml file to like 1000-1500 and that will sort out the problem

**Comment by nickorrnah** [comment]
Thank you for the help!  I hadn't thought of looking at the ctransformers documentation options.
