### ISSUE TITLE
yml config options

### ISSUE THREAD

**Issue by velazquej1** [marella/chatdocs#58]
Where do I find all the available yml config options? for example I see nothing on increasing the threads chatdocs can use but I found a reddit thread that tells what the config options is. I there Documentation, a example file, or some where in the source you can point me to to find this information.

**Comment by nickorrnah** [comment]
Take a look at the marella/ctransformers readme.  I believe it has the documentation you are looking for.  You can also look at the default chatdocs.yml to see some more options.

**Comment by velazquej1** [comment]
Thanks you! that was what I was looking for.
