### ISSUE TITLE
couldn't ingest docs & typer incompatible

### ISSUE THREAD

**Issue by nilvaes** [marella/chatdocs#9]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openapi-python-client 0.13.4 requires typer<0.8.0,>=0.6, but you have typer 0.9.0 which is incompatible.
spacy 3.5.3 requires typer<0.8.0,>=0.3.0, but you have typer 0.9.0 which is incompatible.

1- i had this error when i was trying to '`pip install chatdocs`'
Does it effect my app overall?

2- And when i use it, it looks like a chatpgt, i couldn't ingest any pdf file using `chatdocs add /path/to/documents` (adding a screenshot)
![Screenshot 2023-06-09 124423](https://github.com/marella/chatdocs/assets/90209312/d010249c-e7b7-4b37-9b97-cf021cde5e1d)

**Comment by marella** [comment]
`typer` version shouldn't be an issue.

Can you please share the error/output of `chatdocs add` command.

**Comment by nilvaes** [comment]
add path:
![add path](https://github.com/marella/chatdocs/assets/90209312/de567575-2c74-4518-bc09-39a44ab52ff8)

![Screenshot 2023-06-13 203024](https://github.com/marella/chatdocs/assets/90209312/c99f5b97-19e1-4509-8e69-2038bbb77bab)


![Screenshot 2023-06-13 203253](https://github.com/marella/chatdocs/assets/90209312/7adbcb06-00f8-4b20-baa0-3f811b0627c3)


idk what the problem is but it works like a chatgpt but not too great version of it. I couldn't ingest with this add path command.

**Comment by marella** [comment]
`/path/to/documents` is an example meaning replace it with the actual path to your documents folder. Since you added the document to `examples` folder, it would be:

```sh
chatdocs add examples
```

Tip: You can copy the folder path by selecting it in File Explorer and pressing `ctrl + c` and then if you press `ctrl + v` in Command Prompt it will paste the folder path.

**Comment by nilvaes** [comment]
Thanks a lot! I feel a bit stupid now, but if a beginner similar to me has the same problem, they now know how to correct it. Ingesting documents fixed the problem. Now it answers from the pdf files and shows where he found it. 

Wish you a nice day!!
